"""
BACKPROPAGATION: A Brief Overview

Backpropagation is a fundamental algorithm for training neural networks.
It efficiently computes gradients of the loss function with respect to 
all model parameters using the chain rule of calculus.

Key Concepts:
1. Forward Pass: Input data flows through the network, producing predictions
2. Loss Calculation: Compare predictions with actual values
3. Backward Pass: Compute gradients by applying chain rule from output to input
4. Parameter Update: Adjust weights using gradients (typically with gradient descent)

Mathematical Foundation:
- If we have a composite function f(g(x)), the chain rule states:
    df/dx = df/dg * dg/dx
    
- For a neural network with layers, gradients flow backward as:
    dL/dw = dL/da * da/dz * dz/dw
    where L is loss, a is activation, z is pre-activation, w is weight

Advantages:
- Computational efficiency: O(n) complexity for n parameters
- Generalizes to any network architecture
- Enables training of deep networks

Example Flow:
Input → Layer1 → Layer2 → Output → Loss
    ↓       ↓        ↓        ↓       ↓
Gradient computation flows backward through each layer
"""

print("Backpropagation enables efficient neural network training by computing")
print("gradients of the loss with respect to all parameters in one backward pass.")

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [6]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [1]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
# For Regression Problems
model = Sequential()
model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

# For Classification Problems
# model = Sequential()
# model.add(Dense(2,activation='sigmoid', input_dim=2))
# model.add(Dense(1,activation='sigmoid'))

c:\Users\krish\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[-0.9140887 , -0.26528317],
        [-0.56063175, -0.930449  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.4717847 ],
        [0.37073958]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]]), np.array([0.1, 0.1]), np.array([[0.1], [0.1]]), np.array([0.1])]

In [11]:
model.set_weights(new_weights)

In [12]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0.1, 0.1], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [13]:
optimizer = keras.optimizers.SGD(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mean_squared_error')

In [14]:
model.fit(df.iloc[:,0:-1].values, df.iloc[:,-1].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.0963  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18.8298 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.5419 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0448 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4032 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0263 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9323 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9109 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9419 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8999 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8981 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8633 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8368 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7731 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7289 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━

In [16]:
model.get_weights()

[array([[0.0028864 , 0.0028864 ],
        [0.52202237, 0.52202237]], dtype=float32),
 array([0.11684212, 0.11684212], dtype=float32),
 array([[0.51569784],
        [0.51569784]], dtype=float32),
 array([0.19867958], dtype=float32)]